id: P008139
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC441
  title: 'ས་ཁང་བདག་དབང་སྐོར་གྱི་རྩོད་གླེང་། '
  author: ''
  volumes:
    5ad7f5404e87485f9437e945b0cb1f14:
      image_group_id: I2PD18370
      title: ''
      volume_number: 1
      total_pages: 222
ebook_metadata:
  title: 'ས་ཁང་བདག་དབང་སྐོར་གྱི་རྩོད་གླེང་། '
  author: ''
  sku: P008139
  cover: cover.jpg
  layers:
  - pagination
