id: P008139
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 13:04:04.967990
source_metadata:
  id: bdr:W1AC441
  title: 'ས་ཁང་བདག་དབང་སྐོར་གྱི་རྩོད་གླེང་། '
  author: ''
  volumes:
    fc9da19eb9544928adae8e2a832afaac:
      image_group_id: I2PD18370
      title: Volume 1 of sa khang bdag dbang skor gyi rtsod gleng /
      volume_number: 1
      total_pages: 222
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
